running: dev
domain: http://localhost:8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB  # Tăng dung lượng của toàn bộ request (có thể chứa nhiều file)
  profiles:
    include: common
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/travel
    username: root
    password: tienhoang123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: INFO
    org.apache: WARN
    org.springframework:
      orm:
        jpa: DEBUG
    org.springframework.boot.devtools: INFO
    org.kurento: INFO
    org.kurento.tutorial: INFO
jwt:
  key: nPCD7I_9Qy70joK2D2SomCBkIMuWsG_roxO2ZoO6RPZ81rMTmSUwbcM-s0Zq-lsr
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 420
  access:
    header: Authorization
  refresh:
    header: Refresh

